### PR TITLE
Few small changes

### PR DESCRIPTION
**Pull request by mmattar**
- Updated the ProjectVersion to b07
- Added the ML-Agents package to the manifest since it’s now available as a Preview package
- Updated the installation instructions accordingly
- Updated the Scene to have ManualInput be the active component to match readme.

### CODE REVIEW

**Comment by mmattar** [comment]
@sarahwolf32 - since ML-Agents is now a package, the installation instructions are much simpler with this PR. They can run through manualinput and pre-trained model without needing to install anything other than Unity (and opening the ArmRobot project).

**Comment by vincentpierre** [comment]
In the doc, we say "Unity 2020.1.0b1 or later" but if the project version is 0b7, we need to change that no?

**Comment by mmattar** [comment]
> In the doc, we say "Unity 2020.1.0b1 or later" but if the project version is 0b7, we need to change that no?

Hmm - good point. I'll change the project version to b1.

**Comment by mmattar** [comment]
> > In the doc, we say "Unity 2020.1.0b1 or later" but if the project version is 0b7, we need to change that no?
> 
> Hmm - good point. I'll change the project version to b1.

Sorry, meant to say, I'll change the documentation. No need to have users use an earlier version.

**Pull request merged**
